import type { Page, Product, Store } from "@/lib/types";

// Contenu de départ, créé au premier lancement. Tout est ensuite modifiable depuis /admin.

const product = (p: Partial<Product> & Pick<Product, "id" | "slug" | "name" | "priceCents" | "category">): Product => ({
  subtitle: "",
  compareAtCents: null,
  images: [],
  description: "",
  howToUse: "",
  ingredients: "",
  optionName: "",
  optionValues: [],
  badge: "",
  stock: 100,
  featured: false,
  published: true,
  position: 0,
  ...p,
});

const products: Product[] = [
  product({
    id: "p-elixir-de-nuit",
    slug: "elixir-de-nuit-huile-de-soie",
    name: "Huile de soie L'Élixir de Nuit",
    subtitle: "Visage, corps & cheveux",
    priceCents: 2490,
    category: "soins",
    images: ["/produits/elixir.svg"],
    description:
      "Une huile sèche luxueuse, rapidement absorbée, infusée d'un parfum aphrodisiaque de jasmin et d'ylang-ylang. Elle nourrit intensément la peau et les cheveux, laissant un voile de douceur irrésistible et un fini soyeux, parfait pour les moments d'intimité.\n\n**Teinte universelle et transparente** : cette huile légère n'a pas de teinte propre. Elle se fond sur toutes les carnations pour révéler un éclat naturel et une peau satinée, sans effet autobronzant immédiat.",
    howToUse:
      "Appliquez quelques gouttes au creux de vos mains, chauffez l'huile et massez délicatement sur le corps et les pointes des cheveux. Insistez sur les zones de pulsation (cou, poignets, décolleté) pour exhaler son parfum sensuel.",
    ingredients: "Liste INCI à compléter.",
    badge: "Best seller",
    featured: true,
    position: 1,
  }),
  product({
    id: "p-voile-de-caresse",
    slug: "voile-de-caresse-brume-autobronzante",
    name: "Brume autobronzante Le Voile de Caresse",
    subtitle: "Visage & décolleté · Medium Glow",
    priceCents: 2290,
    category: "autobronzants",
    images: ["/produits/voile.svg"],
    description:
      "Une brume ultrafine et légère, imperceptible sur la peau, qui développe un hâle doré et naturel, sans traces. Son parfum floral et poudré évoque la caresse du soleil sur la peau.\n\n**Medium Glow** : un hâle léger, doré et naturel, comme après une douce journée de printemps.",
    howToUse:
      "Vaporisez légèrement et uniformément sur le visage et le décolleté propres et secs, en tenant le flacon à environ 20 cm. Laissez sécher quelques minutes avant de vous habiller. Pour un résultat optimal, utilisez après avoir exfolié la peau.",
    ingredients: "Liste INCI à compléter.",
    optionName: "Teinte",
    optionValues: ["Medium Glow"],
    featured: true,
    position: 2,
  }),
  product({
    id: "p-mousse-divine",
    slug: "mousse-divine-autobronzante-corps",
    name: "Mousse autobronzante La Mousse Divine",
    subtitle: "Corps, hâle profond · Deep Bronze",
    priceCents: 2990,
    category: "autobronzants",
    images: ["/produits/mousse-divine.webp"],
    description:
      "Une mousse autobronzante légère, facile à appliquer, qui procure un hâle profond et naturel, longue durée. Enrichie en agents hydratants, elle ne dessèche pas la peau. Son parfum gourmand de vanille et de bois de santal vous enveloppe d'une sensualité envoûtante.\n\n**Deep Bronze** : un hâle riche et intense, comme après un long séjour au soleil.",
    howToUse:
      "Appliquez la mousse sur une peau propre, sèche et exfoliée, avec le Gant de Velours pour une répartition homogène. Répartissez uniformément sur tout le corps, par mouvements circulaires. Laissez poser de 4 à 8 heures avant de rincer.",
    ingredients: "Liste INCI à compléter.",
    optionName: "Teinte",
    optionValues: ["Deep Bronze"],
    badge: "Best seller",
    featured: true,
    position: 3,
  }),
  product({
    id: "p-rituel-d-or",
    slug: "rituel-d-or-coffret-decouverte",
    name: "Coffret Le Rituel d'Or",
    subtitle: "Brume, gel douche et lait hydratant",
    priceCents: 4990,
    category: "coffrets",
    images: ["/produits/trousse-rituel.png", "/produits/coffret.svg"],
    description:
      "Le kit complet pour un teint hâlé et une peau sensuellement parfumée, livré dans sa trousse skkin. réutilisable. Il contient :\n\n- Une brume autobronzante visage & décolleté « Le Voile de Caresse » (50 ml)\n- Un mini gel douche soyeux (50 ml) au parfum assorti\n- Un mini lait hydratant sublimateur (50 ml)",
    howToUse:
      "1. Nettoyez votre peau avec le gel douche soyeux.\n2. Séchez bien la peau, puis vaporisez la brume « Le Voile de Caresse ». Laissez sécher.\n3. Appliquez le lait hydratant sublimateur sur le reste du corps pour une douceur et un éclat divins.",
    ingredients: "Liste INCI à compléter.",
    optionName: "Teinte",
    optionValues: ["Medium Glow"],
    badge: "Coffret",
    featured: true,
    position: 4,
  }),
  product({
    id: "p-gant-de-velours",
    slug: "gant-de-velours-applicateur",
    name: "Gant applicateur Le Gant de Velours",
    subtitle: "Pour une application sans traces",
    priceCents: 990,
    category: "accessoires",
    images: ["/produits/gant.svg"],
    description:
      "Un gant applicateur ultra-doux, en velours, pour une application sans traces de nos mousses et brumes autobronzantes. Il protège vos mains et assure un fini impeccable.",
    howToUse:
      "Placez votre main dans le gant. Appliquez la mousse ou la brume autobronzante directement sur le gant ou sur la peau. Répartissez le produit par mouvements circulaires sur tout le corps. Lavez le gant après chaque utilisation.",
    position: 5,
  }),
  product({
    id: "p-caresse-du-soir",
    slug: "caresse-du-soir-deodorant-solide",
    name: "Déodorant solide La Caresse du Soir",
    subtitle: "Rose & bergamote, sans sels d'aluminium",
    priceCents: 1490,
    category: "soins",
    images: ["/produits/deodorant.svg"],
    description:
      "Un déodorant solide naturel et doux, formulé sans sels d'aluminium, pour neutraliser les odeurs et offrir une sensation de fraîcheur et de propreté durable. Son parfum délicat de rose et de bergamote est une véritable caresse pour les sens.",
    howToUse:
      "Appliquez une petite quantité de produit sur une peau propre et sèche, en massant doucement. Le déodorant se fond sur la peau sans laisser de traces blanches.",
    ingredients: "Liste INCI à compléter.",
    position: 6,
  }),
  product({
    id: "p-huile-bronzante",
    slug: "huile-bronzante-le-baiser-dore",
    name: "Huile bronzante Le Baiser Doré",
    subtitle: "Huile parfumée corps · 75 ml",
    priceCents: 2690,
    category: "autobronzants",
    images: ["/produits/huile-bronzante.webp"],
    description:
      "Une huile légère et parfumée qui sublime le hâle et laisse la peau douce et lumineuse. Son applicateur à bille permet de la déposer précisément, sans couler.\n\n*Texte provisoire : modifiez le nom, le prix, le parfum et la description depuis l'admin.*",
    howToUse: "Faites rouler la bille sur la peau propre et sèche, puis massez pour faire pénétrer.",
    ingredients: "Liste INCI à compléter.",
    badge: "Nouveau",
    position: 7,
  }),
  product({
    id: "p-brume-douceur",
    slug: "brume-la-douceur",
    name: "Brume corps & cheveux La Douceur",
    subtitle: "Notes de bonbon rose · corps & cheveux",
    priceCents: 2490,
    category: "soins",
    images: ["/produits/brume-douceur.svg"],
    description:
      "Une brume parfumée légère aux notes gourmandes de bonbon rose, qui laisse sur la peau et les cheveux un sillage doux et joyeux.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez à 20 cm sur le corps et les cheveux, à tout moment de la journée.",
    ingredients: "Liste INCI à compléter.",
    position: 8,
  }),
  product({
    id: "p-brume-fruit-defendu",
    slug: "brume-le-fruit-defendu",
    name: "Brume corps & cheveux Le Fruit Défendu",
    subtitle: "Notes de cerise · corps & cheveux",
    priceCents: 2490,
    category: "soins",
    images: ["/produits/brume-fruit-defendu.png"],
    description:
      "Une brume parfumée aux notes de cerise juteuse, à la fois fruitée et gourmande, pour un sillage irrésistible.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez à 20 cm sur le corps et les cheveux, à tout moment de la journée.",
    ingredients: "Liste INCI à compléter.",
    position: 9,
  }),
  product({
    id: "p-brume-nuit-de-velours",
    slug: "brume-la-nuit-de-velours",
    name: "Brume corps & cheveux La Nuit de Velours",
    subtitle: "Notes de musc · corps & cheveux",
    priceCents: 2490,
    category: "soins",
    images: ["/produits/brume-nuit.svg"],
    description:
      "Une brume parfumée aux notes de musc blanc, enveloppante et sensuelle, qui se pose comme une seconde peau.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez à 20 cm sur le corps et les cheveux, à tout moment de la journée.",
    ingredients: "Liste INCI à compléter.",
    position: 10,
  }),
  product({
    id: "p-coffret-trio-brumes",
    slug: "coffret-trio-de-brumes",
    name: "Coffret Trio de Brumes",
    subtitle: "La Douceur, Le Fruit Défendu et La Nuit de Velours",
    priceCents: 6490,
    compareAtCents: 7470,
    category: "coffrets",
    images: ["/produits/brumes-trio.svg"],
    description:
      "Nos trois brumes corps & cheveux réunies : bonbon rose, cerise et musc, pour changer de parfum selon vos envies.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez à 20 cm sur le corps et les cheveux, à tout moment de la journée.",
    badge: "Coffret",
    position: 11,
  }),
  product({
    id: "p-deodorant-sugar-shower",
    slug: "deodorant-sugar-shower",
    name: "Déodorant Sugar Shower",
    subtitle: "Déodorant en pot, notes sucrées",
    priceCents: 1490,
    category: "soins",
    images: ["/produits/deodorant-sugar-shower.png"],
    description:
      "Un déodorant crème doux, au parfum sucré et gourmand, qui laisse une sensation de fraîcheur et de propreté durable.\n\n*Texte et prix provisoires : modifiez-les depuis l'admin.*",
    howToUse: "Prélevez une noisette du bout des doigts et appliquez sur une peau propre et sèche, en massant doucement.",
    ingredients: "Liste INCI à compléter.",
    badge: "Nouveau",
    position: 12,
  }),
  product({
    id: "p-star-set",
    slug: "coffret-star-set",
    name: "Coffret Star Set",
    subtitle: "Déodorant, brume de parfum et brume H2glow",
    priceCents: 4990,
    category: "coffrets",
    images: ["/produits/star-set.svg"],
    description:
      "Le trio star de skkin. :\n\n- Le Déodorant Sugar Shower\n- Une brume de parfum corps & cheveux\n- La brume H2glow\n\n*Texte et prix provisoires : modifiez-les depuis l'admin.*",
    badge: "Coffret",
    position: 13,
  }),
  product({
    id: "p-pack-5-parfums",
    slug: "coffret-5-eaux-de-parfum",
    name: "Coffret 5 eaux de parfum Mélange DIY",
    subtitle: "Cinq signatures à porter seules ou à mélanger · 5 × 50 ml",
    priceCents: 5990,
    compareAtCents: 7450,
    category: "coffrets",
    images: ["/produits/pack-5-parfums.png"],
    description:
      "Cinq eaux de parfum à porter seules ou à superposer pour créer votre propre mélange.\n\n- **Bronze · Ambre Boisé Épicé** : bois de santal crémeux, résine d'ambre, fève tonka et une touche de cardamome ou de poivre noir. Enveloppant et sensuel.\n- **Rouge · Rose Mystique & Oud** : rose de Damas opulente, bois de oud fumé et une pointe de safran. Puissant et dramatique.\n- **Bleu · Océan Frais & Agrumes** : bergamote et citron pétillants, sel marin, notes ozoniques et cèdre clair. Revigorant.\n- **Noir · Cuir Sombre & Tabac** : cuir tanné, feuilles de tabac, vétiver et une pointe d'encens. Intense et sophistiqué.\n- **Violet · Iris Poudré & Musc** : iris, violette, héliotrope et musc blanc. Doux et élégant.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse:
      "Vaporisez un parfum seul, ou superposez-en deux : une note de fond (Bronze, Noir) puis une note plus légère (Bleu, Violet, Rouge). Testez vos mélanges sur le poignet avant de les porter.",
    ingredients: "Liste INCI à compléter.",
    badge: "Nouveau",
    position: 14,
  }),
  product({
    id: "p-edp-ambre",
    slug: "eau-de-parfum-ambre-boise-epice",
    name: "Eau de parfum Ambre Boisé Épicé",
    subtitle: "Flacon bronze · 50 ml",
    priceCents: 1490,
    category: "parfums",
    images: ["/produits/parfum-ambre.png"],
    description:
      "Bois de santal crémeux, résine d'ambre, fève tonka et une touche de cardamome ou de poivre noir. Une senteur enveloppante et sensuelle.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez sur les points de pulsation (cou, poignets). Superposez-le à un autre parfum de la collection pour créer votre mélange.",
    ingredients: "Liste INCI à compléter.",
    position: 15,
  }),
  product({
    id: "p-edp-rose-oud",
    slug: "eau-de-parfum-rose-mystique-oud",
    name: "Eau de parfum Rose Mystique & Oud",
    subtitle: "Flacon rouge · 50 ml",
    priceCents: 1490,
    category: "parfums",
    images: ["/produits/parfum-rose-oud.png"],
    description:
      "Une rose de Damas opulente et veloutée, associée à la richesse fumée et boisée du oud, avec une pointe de safran. Un parfum puissant et dramatique.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez sur les points de pulsation (cou, poignets). Superposez-le à un autre parfum de la collection pour créer votre mélange.",
    ingredients: "Liste INCI à compléter.",
    position: 16,
  }),
  product({
    id: "p-edp-ocean",
    slug: "eau-de-parfum-ocean-frais-agrumes",
    name: "Eau de parfum Océan Frais & Agrumes",
    subtitle: "Flacon bleu · 50 ml",
    priceCents: 1490,
    category: "parfums",
    images: ["/produits/parfum-ocean.png"],
    description:
      "Un départ pétillant de bergamote et de citron, un cœur de sel marin, d'algues et de notes ozoniques, sur une base de cèdre clair. Un parfum revigorant et vivifiant.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez sur les points de pulsation (cou, poignets). Superposez-le à un autre parfum de la collection pour créer votre mélange.",
    ingredients: "Liste INCI à compléter.",
    position: 17,
  }),
  product({
    id: "p-edp-cuir",
    slug: "eau-de-parfum-cuir-sombre-tabac",
    name: "Eau de parfum Cuir Sombre & Tabac",
    subtitle: "Flacon noir · 50 ml",
    priceCents: 1490,
    category: "parfums",
    images: ["/produits/parfum-cuir.png"],
    description:
      "Des notes de cuir tanné, de feuilles de tabac séchées, de vétiver terreux et une pointe d'encens. Une senteur intense et sophistiquée.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez sur les points de pulsation (cou, poignets). Superposez-le à un autre parfum de la collection pour créer votre mélange.",
    ingredients: "Liste INCI à compléter.",
    position: 18,
  }),
  product({
    id: "p-edp-iris",
    slug: "eau-de-parfum-iris-poudre-musc",
    name: "Eau de parfum Iris Poudré & Musc",
    subtitle: "Flacon violet · 50 ml",
    priceCents: 1490,
    category: "parfums",
    images: ["/produits/parfum-iris.png"],
    description:
      "Une tête d'iris poudré et de violette, un cœur d'héliotrope, sur une base de musc blanc propre et de bois doux. Un parfum doux, réconfortant et élégant.\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse: "Vaporisez sur les points de pulsation (cou, poignets). Superposez-le à un autre parfum de la collection pour créer votre mélange.",
    ingredients: "Liste INCI à compléter.",
    position: 19,
  }),
  product({
    id: "p-musk-intime-candy-floss",
    slug: "parfum-gel-musk-intime-candy-floss",
    name: "Parfum gel Musk Intime Candy Floss",
    subtitle: "Musc & barbe à papa · longue tenue · 20 ml",
    priceCents: 3500,
    category: "parfums",
    images: ["/produits/musk-intime-candy-floss.png"],
    description:
      "Succombez à la tentation d'une douceur irrésistible : un gel-parfum longue tenue qui marie la sophistication du musc à la gourmandise de la barbe à papa. Son tube élégant et discret se glisse dans le sac pour une retouche de sensualité à tout moment.\n\n- **Longue tenue** : la formule gel se fond sur la peau pour une diffusion lente et durable.\n- **Application précise** : l'embout permet de cibler les zones de pulsation.\n- **Texture sensorielle** : un gel non gras, frais et léger, qui pénètre vite sans film collant.\n- **Nomade** : un format compact de 20 ml, facile à emporter.\n\n## Pyramide olfactive\n\n- **Tête** : barbe à papa, fruits rouges\n- **Cœur** : sucre glace, praline\n- **Fond** : musc blanc, vanille, bois doux\n\n*Prix provisoire : modifiez-le depuis l'admin.*",
    howToUse:
      "1. Dévissez le capuchon pour révéler l'embout applicateur.\n2. Pressez délicatement le tube pour faire sortir une petite quantité de gel.\n3. Appliquez par touches sur les zones de pulsation : intérieur des poignets, base du cou, derrière les oreilles, creux du décolleté, intérieur des coudes.\n4. Ne frottez pas vos poignets l'un contre l'autre : le parfum tiendrait moins longtemps.\n5. Revissez bien le capuchon après chaque utilisation.\n\nUsage externe uniquement. Ne pas appliquer sur les muqueuses. Éviter le contact avec les yeux. Conserver à l'abri de la lumière et de la chaleur.",
    ingredients: "Ingrédients clés : musc blanc, extrait de vanille, agents hydratants.\n\nListe INCI complète à compléter.",
    badge: "Nouveau",
    featured: true,
    position: 20,
  }),
];

const pages: Page[] = [
  {
    id: "pg-a-propos",
    slug: "a-propos",
    title: "À propos de SKKIN",
    published: true,
    content:
      "SKKIN est née d'une idée simple : un hâle qui a l'air vrai, sans exposer sa peau au soleil.\n\nNos formules sont pensées pour sécher vite, ne pas laisser de traces et s'estomper de façon régulière.\n\n## Nos engagements\n\n- Formules testées sous contrôle dermatologique *(à adapter)*\n- Déodorant sans sels d'aluminium\n- Non testé sur les animaux *(à adapter)*\n- Fabriqué en *[pays à compléter]*",
  },
  {
    id: "pg-guide",
    slug: "guide-application",
    title: "Guide d'application",
    published: true,
    content:
      "## La veille\n\nExfoliez-vous, puis hydratez les zones sèches (coudes, genoux, chevilles).\n\n## Le jour J\n\n1. Partez d'une peau propre, sèche, sans crème ni déodorant.\n2. **Corps** : appliquez La Mousse Divine avec Le Gant de Velours, zone par zone, par mouvements circulaires. Laissez poser de 4 à 8 heures, puis rincez à l'eau tiède.\n3. **Visage et décolleté** : vaporisez Le Voile de Caresse à environ 20 cm et laissez sécher quelques minutes.\n\n## Pour sublimer\n\nLe soir, massez quelques gouttes de L'Élixir de Nuit sur le corps et les pointes des cheveux pour une peau satinée.",
  },
  {
    id: "pg-faq",
    slug: "faq",
    title: "Questions fréquentes",
    published: true,
    content:
      "## Combien de temps dure le hâle ?\n\nEn général 5 à 7 jours, selon votre peau et votre routine.\n\n## Le produit tache-t-il les vêtements ?\n\nLaissez sécher la mousse ou la brume avant de vous habiller, et portez des vêtements amples jusqu'au rinçage.\n\n## Quelle teinte choisir ?\n\n**Medium Glow** (Le Voile de Caresse) pour un hâle léger et doré sur le visage. **Deep Bronze** (La Mousse Divine) pour un hâle riche et intense sur le corps.\n\n## L'Élixir de Nuit fait-il bronzer ?\n\nNon : c'est une huile transparente, sans effet autobronzant. Elle révèle l'éclat de la peau et la parfume.\n\n## Puis-je utiliser les produits enceinte ?\n\nDemandez l'avis de votre médecin.",
  },
  {
    id: "pg-livraison",
    slug: "livraison-retours",
    title: "Livraison & retours",
    published: true,
    content:
      "## Livraison\n\n- France métropolitaine : 2 à 4 jours ouvrés.\n- Livraison offerte dès le montant indiqué en haut du site.\n\n## Retours\n\nVous disposez de 14 jours après réception pour nous retourner un produit non ouvert. Écrivez-nous à l'adresse de contact pour obtenir l'adresse de retour.",
  },
  {
    id: "pg-contact",
    slug: "contact",
    title: "Contact",
    published: true,
    content:
      "Une question sur une commande ou un produit ? Écrivez-nous : **contact@skkin.fr** *(à modifier)*.\n\nNous répondons du lundi au vendredi, sous 48 heures.",
  },
  {
    id: "pg-cgv",
    slug: "cgv",
    title: "Conditions générales de vente",
    published: true,
    content:
      "*Modèle à compléter et à faire relire : ce texte n'a pas de valeur juridique en l'état.*\n\n## 1. Vendeur\n\n[Raison sociale, forme juridique, adresse, SIRET, numéro de TVA]\n\n## 2. Produits et prix\n\nLes prix sont indiqués en euros TTC. Les frais de livraison sont précisés avant la validation de la commande.\n\n## 3. Commande et paiement\n\n[À compléter]\n\n## 4. Livraison\n\n[À compléter]\n\n## 5. Droit de rétractation\n\nVous disposez de 14 jours à compter de la réception pour exercer votre droit de rétractation. Pour des raisons d'hygiène, les produits descellés après livraison ne peuvent pas être repris.\n\n## 6. Garanties et litiges\n\n[À compléter]",
  },
  {
    id: "pg-mentions",
    slug: "mentions-legales",
    title: "Mentions légales",
    published: true,
    content:
      "*À compléter.*\n\n**Éditeur du site :** [Raison sociale, adresse, SIRET, directeur de la publication]\n\n**Hébergeur :** [Nom, adresse, téléphone de l'hébergeur]\n\n**Contact :** [adresse e-mail]",
  },
  {
    id: "pg-confidentialite",
    slug: "confidentialite",
    title: "Politique de confidentialité",
    published: true,
    content:
      "*À compléter.*\n\nNous collectons uniquement les données nécessaires au traitement de vos commandes : nom, adresse, e-mail et téléphone. Elles ne sont jamais revendues.\n\nVous pouvez demander l'accès, la rectification ou la suppression de vos données en nous écrivant.",
  },
];

export function seedStore(): Store {
  return {
    settings: {
      brandName: "skkin.",
      tagline: "L'autobronzant qui a l'air vrai",
      announcement: "Livraison offerte dès 49 € d'achat",
      logoUrl: "",
      colors: { background: "#f7f3ec", text: "#2a2e2d", primary: "#2a2e2d", accent: "#e8a0b8", muted: "#f6e1e8" },
      hero: {
        title: "Désirée par le soleil, par SKKIN.",
        subtitle: "Des autobronzants qui sèchent vite, ne laissent pas de traces et s'estompent en douceur.",
        ctaLabel: "Découvrir la boutique",
        ctaHref: "/boutique",
        image: "/produits/hero.svg",
      },
      menu: [
        { label: "Boutique", href: "/boutique" },
        { label: "Autobronzants", href: "/boutique?categorie=autobronzants" },
        { label: "Soins & parfums", href: "/boutique?categorie=soins" },
        { label: "Parfums", href: "/boutique?categorie=parfums" },
        { label: "Coffrets", href: "/boutique?categorie=coffrets" },
        { label: "Guide", href: "/pages/guide-application" },
        { label: "À propos", href: "/pages/a-propos" },
      ],
      footerLinks: [
        { label: "FAQ", href: "/pages/faq" },
        { label: "Livraison & retours", href: "/pages/livraison-retours" },
        { label: "Contact", href: "/pages/contact" },
        { label: "CGV", href: "/pages/cgv" },
        { label: "Mentions légales", href: "/pages/mentions-legales" },
        { label: "Confidentialité", href: "/pages/confidentialite" },
      ],
      categories: [
        { slug: "autobronzants", name: "Autobronzants", description: "Brume visage et mousse corps, pour un hâle sans soleil." },
        { slug: "soins", name: "Soins & parfums", description: "Huile de soie et déodorant aux parfums sensuels." },
        { slug: "parfums", name: "Eaux de parfum", description: "Cinq signatures à porter seules ou à mélanger." },
        { slug: "accessoires", name: "Accessoires", description: "Pour une application sans traces." },
        { slug: "coffrets", name: "Coffrets", description: "Les routines complètes, à prix doux." },
      ],
      benefits: [
        { title: "Sans traces", text: "Un hâle doré et naturel, qui s'estompe régulièrement." },
        { title: "Parfums sensuels", text: "Jasmin, vanille, santal, rose : chaque soin a sa signature." },
        { title: "Deux intensités", text: "Medium Glow pour le visage, Deep Bronze pour le corps." },
      ],
      testimonials: [
        { name: "Cliente vérifiée", text: "Exemple d'avis : remplacez-le par un vrai retour client depuis l'admin.", rating: 5 },
        { name: "Cliente vérifiée", text: "Exemple d'avis : ajoutez autant de témoignages que vous voulez.", rating: 5 },
      ],
      contactEmail: "contact@skkin.fr",
      instagram: "",
      tiktok: "",
      footerText: "skkin. · Autobronzants",
      shippingCents: 490,
      freeShippingFromCents: 4900,
      beforeAfter: {
        title: "Avant / Après",
        text: "Un hâle naturel en une seule application.",
        images: ["/avant-apres/visage.png"],
      },
      newsletter: {
        enabled: true,
        title: "-15 % sur votre première commande",
        text: "Inscrivez-vous à la newsletter et recevez votre code de bienvenue.",
        code: "BIENVENUE15",
        percent: 15,
      },
    },
    products,
    pages,
    orders: [],
    subscribers: [],
  };
}
