import type { Page, Product, Store } from "@/lib/types";

// Contenu de départ, créé au premier lancement. Tout est ensuite modifiable depuis /admin.

const product = (p: Partial<Product> & Pick<Product, "id" | "slug" | "name" | "priceCents" | "category">): Product => ({
  subtitle: "",
  compareAtCents: null,
  images: [],
  description: "",
  howToUse: "",
  ingredients: "",
  optionName: "",
  optionValues: [],
  stock: 100,
  featured: false,
  published: true,
  position: 0,
  ...p,
});

const products: Product[] = [
  product({
    id: "p-mousse-glow",
    slug: "mousse-autobronzante-glow",
    name: "Mousse Autobronzante Glow",
    subtitle: "Hâle naturel en 4 à 8 heures",
    priceCents: 2990,
    category: "autobronzants",
    images: ["/produits/mousse.svg"],
    description:
      "Une mousse légère qui sèche vite et ne colle pas. Elle donne un hâle doré et uniforme, sans reflet orangé.\n\n- Séchage rapide\n- Ne tache pas les draps une fois sèche\n- Parfum frais, sans odeur de biscuit",
    howToUse:
      "1. Exfoliez la peau la veille.\n2. Appliquez la mousse au gant, par mouvements circulaires.\n3. Laissez poser de 4 à 8 heures selon l'intensité voulue, puis rincez à l'eau tiède.",
    ingredients: "Liste INCI à compléter.",
    optionName: "Teinte",
    optionValues: ["Medium", "Dark", "Ultra Dark"],
    featured: true,
    position: 1,
  }),
  product({
    id: "p-gouttes-visage",
    slug: "gouttes-bronzantes-visage",
    name: "Gouttes Bronzantes Visage",
    subtitle: "À mélanger à votre crème de jour",
    priceCents: 2790,
    category: "visage",
    images: ["/produits/gouttes.svg"],
    description:
      "Quelques gouttes dans votre soin habituel pour un teint hâlé qui se construit jour après jour. Vous réglez l'intensité en dosant le nombre de gouttes.",
    howToUse: "Mélangez 2 à 4 gouttes à votre crème hydratante, le soir, et appliquez sur le visage et le cou.",
    ingredients: "Liste INCI à compléter.",
    featured: true,
    position: 2,
  }),
  product({
    id: "p-lotion-graduelle",
    slug: "lotion-graduelle-hydratante",
    name: "Lotion Graduelle Hydratante",
    subtitle: "Un hâle progressif, au quotidien",
    priceCents: 2490,
    category: "autobronzants",
    images: ["/produits/lotion.svg"],
    description:
      "Un lait hydratant qui dépose une touche de couleur à chaque application. Idéal pour débuter ou pour entretenir son hâle.",
    howToUse: "Appliquez chaque jour sur peau propre et sèche jusqu'à obtenir la teinte souhaitée. Lavez-vous les mains après application.",
    ingredients: "Liste INCI à compléter.",
    featured: true,
    position: 3,
  }),
  product({
    id: "p-brume-express",
    slug: "brume-bronzante-express",
    name: "Brume Bronzante Express",
    subtitle: "Pour le corps et les zones difficiles d'accès",
    priceCents: 2690,
    category: "autobronzants",
    images: ["/produits/brume.svg"],
    description: "Un spray à 360° qui se vaporise même tête en bas : parfait pour le dos et les jambes.",
    howToUse: "Vaporisez à 15 cm de la peau, puis estompez au gant. Rincez après 2 à 6 heures.",
    ingredients: "Liste INCI à compléter.",
    position: 4,
  }),
  product({
    id: "p-gommage",
    slug: "gommage-preparateur",
    name: "Gommage Préparateur",
    subtitle: "Une base nette pour un hâle uniforme",
    priceCents: 1990,
    category: "soins",
    images: ["/produits/gommage.svg"],
    description: "Un gommage aux grains fins qui élimine les cellules mortes et les restes d'ancien bronzage.",
    howToUse: "Massez sur peau humide, insistez sur les coudes, genoux et chevilles, puis rincez.",
    ingredients: "Liste INCI à compléter.",
    position: 5,
  }),
  product({
    id: "p-lait-prolongateur",
    slug: "lait-prolongateur-de-bronzage",
    name: "Lait Prolongateur",
    subtitle: "Garde votre hâle plus longtemps",
    priceCents: 2190,
    category: "soins",
    images: ["/produits/lait.svg"],
    description: "Un soin riche et non gras qui nourrit la peau et ralentit l'estompage du bronzage.",
    howToUse: "Appliquez matin et soir sur l'ensemble du corps.",
    ingredients: "Liste INCI à compléter.",
    position: 6,
  }),
  product({
    id: "p-gant-velours",
    slug: "gant-application-velours",
    name: "Gant d'application Velours",
    subtitle: "Zéro trace, mains propres",
    priceCents: 990,
    category: "accessoires",
    images: ["/produits/gant.svg"],
    description: "Un gant doux double face qui répartit le produit sans traces. Lavable en machine à 30 °C.",
    position: 7,
  }),
  product({
    id: "p-pinceau-kabuki",
    slug: "pinceau-kabuki-visage",
    name: "Pinceau Kabuki Visage",
    subtitle: "Pour estomper la racine des cheveux et les sourcils",
    priceCents: 1290,
    category: "accessoires",
    images: ["/produits/pinceau.svg"],
    description: "Des fibres synthétiques denses pour fondre l'autobronzant sur le visage, les mains et les pieds.",
    position: 8,
  }),
  product({
    id: "p-kit-glow",
    slug: "kit-glow-complet",
    name: "Kit Glow Complet",
    subtitle: "Gommage, mousse, gant et lait prolongateur",
    priceCents: 5990,
    compareAtCents: 8160,
    category: "coffrets",
    images: ["/produits/kit.svg"],
    description: "Tout le rituel en un seul coffret : préparer, bronzer, appliquer, entretenir.",
    featured: true,
    position: 9,
  }),
  product({
    id: "p-duo-visage-corps",
    slug: "duo-visage-corps",
    name: "Duo Visage & Corps",
    subtitle: "Mousse Glow + Gouttes Visage",
    priceCents: 4990,
    compareAtCents: 5780,
    category: "coffrets",
    images: ["/produits/duo.svg"],
    description: "Le duo pour un hâle harmonieux de la tête aux pieds.",
    optionName: "Teinte de la mousse",
    optionValues: ["Medium", "Dark", "Ultra Dark"],
    position: 10,
  }),
];

const pages: Page[] = [
  {
    id: "pg-a-propos",
    slug: "a-propos",
    title: "À propos de SKKIN",
    published: true,
    content:
      "SKKIN est née d'une idée simple : un hâle qui a l'air vrai, sans exposer sa peau au soleil.\n\nNos formules sont pensées pour sécher vite, ne pas laisser de traces et s'estomper de façon régulière.\n\n## Nos engagements\n\n- Formules testées sous contrôle dermatologique *(à adapter)*\n- Non testé sur les animaux *(à adapter)*\n- Fabriqué en *[pays à compléter]*",
  },
  {
    id: "pg-guide",
    slug: "guide-application",
    title: "Guide d'application",
    published: true,
    content:
      "## La veille\n\nExfoliez-vous avec le Gommage Préparateur, puis hydratez les zones sèches (coudes, genoux, chevilles).\n\n## Le jour J\n\n1. Partez d'une peau propre, sèche, sans crème ni déodorant.\n2. Appliquez la mousse au gant, zone par zone, par mouvements circulaires.\n3. Estompez avec le reste du gant sur les mains, les pieds et le visage.\n4. Laissez poser de 4 à 8 heures, puis rincez à l'eau tiède sans savon.\n\n## Pour entretenir\n\nHydratez chaque jour avec le Lait Prolongateur.",
  },
  {
    id: "pg-faq",
    slug: "faq",
    title: "Questions fréquentes",
    published: true,
    content:
      "## Combien de temps dure le hâle ?\n\nEn général 5 à 7 jours, selon votre peau et votre routine.\n\n## Le produit tache-t-il les vêtements ?\n\nAttendez que la mousse soit sèche (environ 2 minutes) avant de vous habiller. Portez des vêtements amples jusqu'au rinçage.\n\n## Quelle teinte choisir ?\n\n**Medium** pour une peau claire, **Dark** pour un hâle prononcé, **Ultra Dark** pour les peaux mates ou un effet très bronzé.\n\n## Puis-je l'utiliser enceinte ?\n\nDemandez l'avis de votre médecin.",
  },
  {
    id: "pg-livraison",
    slug: "livraison-retours",
    title: "Livraison & retours",
    published: true,
    content:
      "## Livraison\n\n- France métropolitaine : 2 à 4 jours ouvrés.\n- Livraison offerte dès le montant indiqué en haut du site.\n\n## Retours\n\nVous disposez de 14 jours après réception pour nous retourner un produit non ouvert. Écrivez-nous à l'adresse de contact pour obtenir l'adresse de retour.",
  },
  {
    id: "pg-contact",
    slug: "contact",
    title: "Contact",
    published: true,
    content:
      "Une question sur une commande ou un produit ? Écrivez-nous : **contact@skkin.fr** *(à modifier)*.\n\nNous répondons du lundi au vendredi, sous 48 heures.",
  },
  {
    id: "pg-cgv",
    slug: "cgv",
    title: "Conditions générales de vente",
    published: true,
    content:
      "*Modèle à compléter et à faire relire : ce texte n'a pas de valeur juridique en l'état.*\n\n## 1. Vendeur\n\n[Raison sociale, forme juridique, adresse, SIRET, numéro de TVA]\n\n## 2. Produits et prix\n\nLes prix sont indiqués en euros TTC. Les frais de livraison sont précisés avant la validation de la commande.\n\n## 3. Commande et paiement\n\n[À compléter]\n\n## 4. Livraison\n\n[À compléter]\n\n## 5. Droit de rétractation\n\nVous disposez de 14 jours à compter de la réception pour exercer votre droit de rétractation. Pour des raisons d'hygiène, les produits descellés après livraison ne peuvent pas être repris.\n\n## 6. Garanties et litiges\n\n[À compléter]",
  },
  {
    id: "pg-mentions",
    slug: "mentions-legales",
    title: "Mentions légales",
    published: true,
    content:
      "*À compléter.*\n\n**Éditeur du site :** [Raison sociale, adresse, SIRET, directeur de la publication]\n\n**Hébergeur :** [Nom, adresse, téléphone de l'hébergeur]\n\n**Contact :** [adresse e-mail]",
  },
  {
    id: "pg-confidentialite",
    slug: "confidentialite",
    title: "Politique de confidentialité",
    published: true,
    content:
      "*À compléter.*\n\nNous collectons uniquement les données nécessaires au traitement de vos commandes : nom, adresse, e-mail et téléphone. Elles ne sont jamais revendues.\n\nVous pouvez demander l'accès, la rectification ou la suppression de vos données en nous écrivant.",
  },
];

export function seedStore(): Store {
  return {
    settings: {
      brandName: "skkin.",
      tagline: "L'autobronzant qui a l'air vrai",
      announcement: "Livraison offerte dès 49 € d'achat",
      logoUrl: "",
      colors: { background: "#f7f3ec", text: "#2a2e2d", primary: "#2a2e2d", accent: "#e8a0b8", muted: "#f6e1e8" },
      hero: {
        title: "Désirée par le soleil, par SKKIN.",
        subtitle: "Des autobronzants qui sèchent vite, ne laissent pas de traces et s'estompent en douceur.",
        ctaLabel: "Découvrir la boutique",
        ctaHref: "/boutique",
        image: "/produits/hero.svg",
      },
      menu: [
        { label: "Boutique", href: "/boutique" },
        { label: "Autobronzants", href: "/boutique?categorie=autobronzants" },
        { label: "Coffrets", href: "/boutique?categorie=coffrets" },
        { label: "Guide", href: "/pages/guide-application" },
        { label: "À propos", href: "/pages/a-propos" },
      ],
      footerLinks: [
        { label: "FAQ", href: "/pages/faq" },
        { label: "Livraison & retours", href: "/pages/livraison-retours" },
        { label: "Contact", href: "/pages/contact" },
        { label: "CGV", href: "/pages/cgv" },
        { label: "Mentions légales", href: "/pages/mentions-legales" },
        { label: "Confidentialité", href: "/pages/confidentialite" },
      ],
      categories: [
        { slug: "autobronzants", name: "Autobronzants", description: "Mousses, lotions et brumes pour le corps." },
        { slug: "visage", name: "Visage", description: "Un teint hâlé, dosé à la goutte près." },
        { slug: "soins", name: "Préparer & entretenir", description: "Avant et après l'application." },
        { slug: "accessoires", name: "Accessoires", description: "Pour une application sans traces." },
        { slug: "coffrets", name: "Coffrets", description: "Les routines complètes, à prix doux." },
      ],
      benefits: [
        { title: "Séchage en 2 minutes", text: "Vous vous habillez presque tout de suite." },
        { title: "Sans traces", text: "Une couleur uniforme, qui s'estompe régulièrement." },
        { title: "Teinte sur mesure", text: "Trois intensités, de Medium à Ultra Dark." },
      ],
      testimonials: [
        { name: "Cliente vérifiée", text: "Exemple d'avis : remplacez-le par un vrai retour client depuis l'admin.", rating: 5 },
        { name: "Cliente vérifiée", text: "Exemple d'avis : ajoutez autant de témoignages que vous voulez.", rating: 5 },
      ],
      contactEmail: "contact@skkin.fr",
      instagram: "",
      tiktok: "",
      footerText: "skkin. · Autobronzants",
      shippingCents: 490,
      freeShippingFromCents: 4900,
      beforeAfter: {
        title: "Avant / Après",
        text: "Un hâle naturel en une seule application.",
        images: ["/avant-apres/visage.png"],
      },
      newsletter: {
        enabled: true,
        title: "-15 % sur votre première commande",
        text: "Inscrivez-vous à la newsletter et recevez votre code de bienvenue.",
        code: "BIENVENUE15",
        percent: 15,
      },
    },
    products,
    pages,
    orders: [],
    subscribers: [],
  };
}
