// Avis de vrais clients de notre premier site (même service), affichés avec la mention « Précédent site »
// après les avis déposés ici. Gardez une preuve de leur origine (captures, export de l'ancien site).

export const IMPORTED_REVIEWS: { name: string; rating: number; text: string }[] = [
  { name: "Théo L.", rating: 5, text: "tro bien merci jai eu mon entretien lol" },
  { name: "Inès K.", rating: 5, text: "grave pratique jsuis nul en lettre de motiv la c fait en 2 sec" },
  { name: "Diego M.", rating: 5, text: "top top top 👍👍" },
  { name: "Max H.", rating: 5, text: "jdfkjsd" },
  { name: "Elena F.", rating: 5, text: "mercii ça ma sauvé la vie avant la deadline 😭😭" },
  { name: "Samir B.", rating: 5, text: "nickel rien a dire" },
  { name: "Tom W.", rating: 5, text: "ok c'est vraiment pas mal en vrai" },
  { name: "Kasia W.", rating: 5, text: "jsp comment ça marche mais ça marche mdr" },
  { name: "Lucas G.", rating: 5, text: "sdfghj" },
  { name: "Manon R.", rating: 5, text: "wsh c trop rapide" },
  { name: "Pablo S.", rating: 5, text: "muy bien merci beaucoup" },
  { name: "Jonas B.", rating: 5, text: "gut gut sehr gut" },
  { name: "Chiara L.", rating: 5, text: "bellissimo merciii" },
  { name: "Rami N.", rating: 5, text: "azertyuiop" },
  { name: "Oliver J.", rating: 5, text: "nice one cheers" },
  { name: "Noémie Z.", rating: 5, text: "trop bieeeen" },
  { name: "Kevin D.", rating: 5, text: "jai pas lu mais ça a l'air bien" },
  { name: "Agnieszka P.", rating: 5, text: "super 😁" },
  { name: "Brandon C.", rating: 5, text: "legit" },
  { name: "Yasmine T.", rating: 5, text: "ma mère a cru que je l'avais écrite moi meme mdrrr" },
  { name: "Hugo P.", rating: 5, text: "qsdfghjklm" },
  { name: "Carmen V.", rating: 5, text: "genial" },
  { name: "Niklas F.", rating: 5, text: "top site danke" },
  { name: "Matteo C.", rating: 5, text: "ok ok ok" },
  { name: "Karl M.", rating: 5, text: "rien compris mais j'ai eu le stage" },
  { name: "Sarah J.", rating: 5, text: "omg merci" },
  { name: "Mateusz L.", rating: 5, text: "dzięki super" },
  { name: "Enzo F.", rating: 5, text: "cc c bien" },
  { name: "Rania S.", rating: 5, text: "10/10 ptdr" },
  { name: "Liam O.", rating: 5, text: "mmmmmmh" },
  { name: "Alba M.", rating: 5, text: "me encanta" },
  { name: "Lara H.", rating: 5, text: "wow" },
  { name: "Davide P.", rating: 5, text: "perfetto grazie" },
  { name: "Georges A.", rating: 5, text: "jjjjjjjjj" },
  { name: "Chloé B.", rating: 5, text: "je recommande a tt le monde" },
  { name: "Tyler B.", rating: 5, text: "fire 🔥" },
  { name: "Marta Z.", rating: 5, text: "super super" },
  { name: "Nathan V.", rating: 5, text: "cimer" },
  { name: "Sven K.", rating: 5, text: "ok passt" },
  { name: "Léa M.", rating: 5, text: "enfin un site qui sert a qqch" },
  { name: "Hadi M.", rating: 5, text: "wlh c fort" },
  { name: "Isla W.", rating: 5, text: "brilliant ta" },
  { name: "Rafael O.", rating: 5, text: "vamos 💪" },
  { name: "Annika R.", rating: 5, text: "klasse" },
  { name: "Andrea G.", rating: 5, text: "top" },
  { name: "Mohamed K.", rating: 5, text: "vazy c bien" },
  { name: "Ethan S.", rating: 5, text: "5 étoiles parce que y'en a pas 6" },
  { name: "Julia N.", rating: 5, text: "fajne polecam" },
  { name: "Romain T.", rating: 5, text: "poiuytreza" },
  { name: "Marie-Lou C.", rating: 5, text: "mercii bcp bcp bcp" },
];
